concord:
  kafka:
    producer:
      enabled: true
      bootstrap-servers: localhost:9092
      
      security:
        protocol: PLAINTEXT  # PLAINTEXT, SASL_SSL, SSL, SASL_PLAINTEXT
        mechanism: PLAIN     # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
        username: ${KAFKA_USERNAME:}
        password: ${KAFKA_PASSWORD:}
        truststore: ${KAFKA_TRUSTSTORE:}
        truststore-password: ${KAFKA_TRUSTSTORE_PASSWORD:}
        keystore: ${KAFKA_KEYSTORE:}
        keystore-password: ${KAFKA_KEYSTORE_PASSWORD:}
      
      serialization:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        add-type-headers: true
        properties:
          spring.json.add.type.headers: true
      
      retry:
        attempts: 3
        backoff: 1000ms
        max-backoff: 10000ms
        backoff-multiplier: 2.0
        enable-idempotence: true
        max-in-flight-requests-per-connection: 5
      
      metrics:
        enabled: true
        prefix: concord.kafka.producer
        recording-level: 30s
        tags:
          application: ${spring.application.name:my-service}
          environment: ${spring.profiles.active:development}
          version: ${spring.application.version:unknown}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
